name: Create Release
on: 
  push:
    branches:
      - main
jobs:
  get-flutter:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      - run: flutter --version
  build-android:
    runs-on: macos-latest
    needs: get-flutter
    steps:
    - run: flutter build apk
  build-ios:
    runs-on: macos-latest
    needs: get-flutter
    steps:
      - run: flutter build ios --release --no-codesign
  build-web:
    runs-on: macos-latest
    needs: get-flutter
    steps:
    - run: flutter build web --wasm
  build-macos:
    runs-on: macos-latest
    needs: get-flutter
    steps:
      - run: flutter build macos
  
