name: Create Release
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  get-flutter:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      - run: flutter --version
      - run: flutter build apk --target-platform=android-arm64
      - run: flutter build ios --release --no-codesign
      - run: flutter build macos
      - run: flutter build web --wasm
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          allowUpdates: true
          # bodyFile: "releaseNotes.md"
      # - uses: FirebaseExtended/action-hosting-deploy@v0
      #   with:
      #     firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
      #     projectId: your-Firebase-project-ID
      #     channelId: live

      
  
